
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
        cache: 'npm'
    - run: npm run deploy
